apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configured
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-configured
  template:
    metadata:
      labels:
        app: nginx-configured
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: nginx-config